# config for https://gitea.com/gitea/changelog to generate CHANGELOG.md

# The full repository name
repo: anbraten/test-ready-release-go

# Service type (gitea or github)
service: github

# Changelog groups and which labeled PRs to add to each group
groups:
  - name: BREAKING
    labels:
      - breaking
  - name: FEATURES
    labels:
      - feature
  - name: BUGFIXES
    labels:
      - bug
  - name: ENHANCEMENTS
    labels:
      - enhancement
  - name: MISC
    default: true

# regex indicating which labels to skip for the changelog
skip-labels: skip-changelog|backport
