pipeline:
  release:
    image: anbraten/plugin-ready-release-go
    pull: true
    settings:
      release_branch: main
      forge_type: github
      github_token:
        from_secret: GITHUB_TOKEN
    when:
      event: push
      branch: main
