steps:
  test:
    image: alpine
    commands:
      - echo "Hello, World!"
      - pwd
      - cd
      - pwd
  release:
    image: anbraten/plugin-ready-release-go
    pull: true
    settings:
      git_email: owners@woodpecker-ci.org
      github_token:
        from_secret: GITHUB_TOKEN

when:
  - event: push
    branch: ${CI_REPO_DEFAULT_BRANCH}
  - event: manual
    evaluate: 'TASK == "release-helper"'
